# Generated by Django 3.0 on 2022-01-07 09:50

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='short_title', unique=True)),
                ('discription', models.TextField(default='Done')),
                ('file', models.FileField(default='img.jpg', upload_to='Banners/')),
                ('extension', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='category', unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('Image', models.ImageField(blank=True, default='default-product.png', upload_to='categoryimages/')),
                ('status', models.CharField(default=0, max_length=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='swooee.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='static_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page', models.TextField(default='new.html')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True)),
                ('discription', models.TextField(default='Done')),
                ('Image', models.ImageField(default='abc.jpg', upload_to='staticPages/')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='email', unique=True)),
                ('password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('checkbox', models.CharField(default='Not Verified', max_length=1)),
                ('Image', models.ImageField(blank=True, default='default-product.png', upload_to='userimages/')),
                ('status', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True)),
                ('discription', models.CharField(max_length=255)),
                ('Image', models.ImageField(default='abc.jpg', upload_to='productimages/')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('amazon', models.CharField(max_length=200)),
                ('amazon_sell_price', models.CharField(max_length=20)),
                ('amazon_MRP', models.CharField(max_length=20)),
                ('awin', models.CharField(max_length=200)),
                ('awin_sell_price', models.CharField(max_length=20)),
                ('awin_MRP', models.CharField(max_length=20)),
                ('ebay', models.CharField(max_length=200)),
                ('ebay_sell_price', models.CharField(max_length=20)),
                ('ebay_MRP', models.CharField(max_length=20)),
                ('walmart', models.CharField(max_length=200)),
                ('walmart_sell_price', models.CharField(max_length=20)),
                ('walmart_MRP', models.CharField(max_length=20)),
                ('youtube', models.CharField(max_length=200)),
                ('status', models.CharField(default=0, max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swooee.Categories')),
            ],
        ),
    ]
