# Generated by Django 3.0 on 2022-01-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swooee', '0002_auto_20220107_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='password',
            field=models.CharField(default='Admin123', max_length=30),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='username',
            field=models.CharField(default='Admin', max_length=25),
        ),
    ]
