# Generated by Django 3.0 on 2022-01-10 13:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swooee', '0005_auto_20220110_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='contain',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='static_page',
            name='contain',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
